styles = {
  h1: { color: 'white' },
  body: {
    margin: '0',
    padding: '0',
    background:
      'linear-gradient(\n        15deg,\n        rgba(41, 41, 41, 1) 4%,\n        rgba(49, 49, 49, 1) 24%,\n        rgba(128, 128, 128, 1) 64%,\n        rgba(138, 138, 138, 1) 70%,\n        rgba(230, 230, 230, 1) 81%,\n        rgba(255, 255, 255, 1) 86%,\n        rgba(220, 220, 220, 1) 89%,\n        rgba(230, 230, 230, 1) 100%\n    )',
    backgroundColor: '#09a8ff',
    backgroundBlendMode: 'overlay',
  },
  root: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100vh',
  },
  pokedex: {
    backgroundColor: '#e61515',
    width: '848px',
    margin: '0 auto',
    padding: '1em',
    borderRadius: '15px',
    border: 'double black 10px',
    display: 'flex',
  },
  panel: {
    width: '359px',
    padding: '10px',
    border: 'inset #b31818 3px',
    borderRadius: '3px',
    display: 'flex',
    flexDirection: 'column',
  },
  right_panel: { padding: '0', width: '379px' },
  panel_row: {
    display: 'flex',
    borderBottom: 'groove #757575 3px',
    justifyContent: 'space-evenly',
  },
  panel_row_last_child: {
    borderTop: 'groove #757575 3px',
    borderBottom: 'none',
  },
  divider: { borderRadius: '4px', border: 'solid #2d0d0d 2px' },
  hinge: {
    background:
      'linear-gradient(90deg, #891313 0, #b31818 30%, #e61515 45%, #fd5555 65%, #e61515 95%)',
    borderRightColor: '#fd5555',
    borderTopColor: '#fd5555',
    flex: '10',
    width: '100%',
    borderLeftColor: '#5f1010',
  },
  gap_first_child: { borderRadius: '0 0 5px 5px', borderTop: 'none' },
  gap_last_child: { borderRadius: '5px 5px 0 0' },
  gap: {
    background:
      'linear-gradient(90deg, #460f0f 0, #891313 30%, #b31818 45%, #fd5555 65%, #b31818 95%)',
    borderTopColor: '#891313',
    borderRightColor: '#b31818',
    flex: '1',
    width: '95%',
  },
  screen: {
    background:
      'linear-gradient(14deg, rgb(165, 205, 83) 60%, rgb(193, 217, 144) 65%)',
    padding: '5px',
    borderRadius: '3px',
    fontFamily: '"VT323"',
    border: 'inset #879a65 3px',
  },
  pokemon_name: {
    fontSize: '28px',
    letterSpacing: '4px',
    textTransform: 'capitalize',
    height: '45px',
    boxSizing: 'border-box',
  },
  name_no: { float: 'right', textTransform: 'lowercase' },
  pokemon_description: {
    fontSize: '18px',
    letterSpacing: '0',
    minHeight: '115px',
    boxSizing: 'border-box',
    flex: '1',
  },
  pokemon_sprite: {
    width: '100%',
    display: 'flex',
    imageRendering: 'pixelated',
    border: 'inset #9aa28b 3px',
    borderRadius: '5px',
    margin: '10px 0',
    boxSizing: 'border-box',
    background:
      'linear-gradient(15deg, #cad5b5 64%, #dde2d4 70%, #dde2d4 81%, #fff 86%, #dde2d4 89%, #dde2d4 100%)',
  },
  sprite_controls: {
    display: 'flex',
    justifyContent: 'space-around',
    fontFamily: '"Staatliches", cursive',
    marginBottom: '10px',
  },
  sprite_control: { transform: 'rotate(-60deg)' },
  sprite_control_hover: { borderColor: '#b8ed7c' },
  sprite_control_active: { borderColor: '#f4fcb9' },
  sprite_controls_shiny: { transform: 'rotate(0)' },
  sprite_control_selected: { borderColor: '#b8ed7c' },
  pokemon_sprite_small: { height: '120px', width: '120px', margin: '3px 0' },
  type: {
    color: 'rgba(0, 0, 0, 0.9)',
    textTransform: 'capitalize',
    fontSize: '1.25em',
    padding: '2px',
    margin: '2px',
    border: 'groove #757575 3px',
    borderRadius: '10px',
    width: '150px',
    fontFamily: '"Staatliches", cursive',
    textAlign: 'center',
    letterSpacing: '2px',
    textShadow: 'rgba(255, 255, 255, 0.3) -1px 1px',
    alignSelf: 'center',
    background:
      'linear-gradient(\n        15deg,\n        rgba(128, 128, 128, 0.5) 64%,\n        rgba(138, 138, 138, 0.5) 70%,\n        rgba(230, 230, 230, 0.5) 81%,\n        rgba(255, 255, 255, 0.5) 86%,\n        rgba(220, 220, 220, 0.5) 89%,\n        rgba(230, 230, 230, 0.5) 100%\n    )',
    backgroundBlendMode: 'hard-light',
  },
  panel_header: {
    textTransform: 'capitalize',
    fontSize: '1.25em',
    padding: '5px',
    fontFamily: '"Staatliches", cursive',
    letterSpacing: '2px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    background:
      'linear-gradient(14deg, #460f0f 0, #891313 30%, #b31818 45%, #fd5555 65%, #b31818 95%)',
    border: 'groove #e61515 3px',
    borderWidth: '3px 2px',
    textShadow: '#fd5555 -1px 1px',
  },
  type_list: {
    display: 'flex',
    flexDirection: 'column',
    borderLeft: 'groove #757575 3px',
    flex: '1',
  },
  type_box: {
    display: 'flex',
    flexDirection: 'column',
    flex: '1',
    justifyContent: 'space-evenly',
    background: 'linear-gradient(14deg, #afafaf 50%, #ffffff 80%, #afafaf 90%)',
    borderTop: 'groove #757575 3px',
  },
  stats: {
    width: '150px',
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    margin: '5px',
    flex: '1',
  },
  stat_line: { fontSize: '17px', textTransform: 'capitalize' },
  panel_evo: { flexWrap: 'wrap' },
  empty_evo: {
    background:
      'linear-gradient(15deg, #83887b 64%, #8b8f81 70%, #8b8f81 81%, #babfb1 86%, #8b8f81 89%, #8b8f81 100%)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  poke_ball: {
    border: 'solid black 4px',
    background: 'black',
    borderRadius: '50%',
    height: '50px',
    width: '50px',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    alignItems: 'center',
    position: 'relative',
    opacity: '0.8',
  },
  poke_ball_top: {
    background: '#83887a',
    flex: '1',
    width: '100%',
    opacity: '0.3',
  },
  poke_ball_center: {
    display: 'flex',
    width: '22px',
    height: '22px',
    border: 'solid black 4px',
    borderRadius: '50%',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: '10px',
  },
  poke_ball_dot: {
    height: '10px',
    width: '10px',
    borderRadius: '50%',
    background: 'black',
    border: 'solid #83887a 6px',
  },
  poke_ball_bottom: { background: '#83887a', flex: '1', width: '100%' },
  evo_header: { width: '100%', marginBottom: '2px' },
  evo_num: {
    fontFamily: '"Staatliches", cursive',
    fontSize: '1.25em',
    letterSpacing: '2px',
    background: 'transparent',
    border: 'none',
    textShadow: '#e78181 -1px 1px',
  },
  evo_name: {
    width: 'auto',
    padding: '3px',
    marginBottom: '3px',
    textAlign: 'right',
  },
  blue_buttons: { flexWrap: 'wrap', padding: '5px' },
  blue_button: {
    height: '30px',
    flex: '1 1 16%',
    margin: '3px',
    border: 'groove #6c96e6 3px',
    borderRadius: '5px',
    background:
      'linear-gradient(\n        15deg,\n        rgba(128, 128, 128, 0.5) 64%,\n        rgba(138, 138, 138, 0.5) 70%,\n        rgba(230, 230, 230, 0.5) 81%,\n        rgba(255, 255, 255, 0.5) 86%,\n        rgba(220, 220, 220, 0.5) 89%,\n        rgba(230, 230, 230, 0.5) 100%\n    )',
    backgroundBlendMode: 'hard-light',
    backgroundColor: '#09a8ff',
  },
  move_list: { display: 'flex' },
  move_screen: { margin: '3px', padding: '10px 20px', flex: '1' },
  move_head: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    marginBottom: '3px',
  },
  move_name: {
    fontSize: '24px',
    borderBottom: 'solid black 2px',
    marginBottom: '3px',
    textAlign: 'center',
    textTransform: 'capitalize',
  },
  move_type: {
    fontSize: '18px',
    textTransform: 'uppercase',
    border: 'solid black 2px',
    borderRadius: '7px',
    padding: '2px 10px',
    textAlign: 'center',
  },
  move_body: { display: 'flex', justifyContent: 'space-between' },
  move_learn: { float: 'right', marginRight: '3px' },
  move_status: {
    textTransform: 'capitalize',
    marginRight: '3px',
    marginTop: '3px',
  },
  move_controls: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    padding: '0 10px 0 7px',
  },
  move_arrow: { transform: 'rotate(-60deg)' },
  move_arrow_first_child: { paddingBottom: '5px' },
  move_arrow_last_child: { paddingTop: '1px' },
  move_arrow_hover: { borderColor: 'rgb(184, 237, 124)' },
  move_arrow_active: { borderColor: 'rgb(244, 252, 185)' },
  down_arrow: { background: 'yellow' },
  flex_center: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  controls: {
    display: 'flex',
    justifyContent: 'space-around',
    padding: '15px',
  },
  button: {
    padding: '5px',
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    border: 'outset rgb(248, 187, 187) 6px',
    transform: 'rotate(60deg)',
    background:
      'radial-gradient(\n        circle farthest-corner at 40% 25%,\n        rgb(218, 237, 241) 9%,\n        rgb(124, 214, 237) 20%,\n        rgb(64, 90, 165) 62%,\n        rgb(43, 125, 196) 100%\n    )',
    cursor: 'pointer',
  },
  button_hover: {
    background:
      'radial-gradient(\n        circle farthest-corner at 40% 25%,\n        rgb(233, 241, 218) 9%,\n        rgb(184, 237, 124) 20%,\n        rgb(64, 165, 106) 62%,\n        rgb(43, 196, 145) 100%\n    )',
  },
  button_active: {
    background:
      'radial-gradient(\n        circle farthest-corner at 40% 25%,\n        rgb(229, 255, 181) 9%,\n        rgb(204, 237, 124) 20%,\n        rgb(103, 165, 64) 62%,\n        rgb(66, 204, 40) 100%\n    )',
  },
  button__after: {
    border: 'groove #460f0f 5px',
    content: '""',
    width: '60px',
    height: '60px',
    position: 'absolute',
    borderRadius: '50%',
    left: '-10px',
    top: '-10px',
    borderStyle: 'double',
    opacity: '0.75',
  },
  prev: { borderRight: '30px solid white' },
  num: { color: 'blue' },
  next: { borderLeft: '30px solid white' },
  num_input: {
    width: '50px',
    fontSize: '20px',
    height: '30px',
    textAlign: 'right',
    alignSelf: 'center',
  },
  submit: {
    width: '66px',
    height: '18px',
    border: 'groove #5f845e 3px',
    backgroundColor: '#5ed75e',
    borderRadius: '20px',
    boxSizing: 'border-box',
    marginTop: '3px',
    cursor: 'pointer',
  },
  submit_hover: { borderColor: '#85ec4d' },
  normal: { backgroundColor: '#bfbfbf' },
  fighting: { backgroundColor: '#d87c58' },
  flying: { backgroundColor: '#999ade' },
  poison: { backgroundColor: '#925192' },
  ground: { backgroundColor: '#dea761' },
  rock: { backgroundColor: '#897864' },
  bug: { backgroundColor: '#b1c967' },
  ghost: { backgroundColor: '#c195dc' },
  steel: { backgroundColor: '#49769c' },
  fire: { backgroundColor: '#cf1414' },
  water: { backgroundColor: '#1689de' },
  grass: { backgroundColor: '#47a047' },
  electric: { backgroundColor: '#e6b700' },
  psychic: { backgroundColor: '#fa43b8' },
  ice: { backgroundColor: '#98c3de' },
  dragon: { backgroundColor: '#89315d' },
  dark: { backgroundColor: '#282433' },
  fairy: { backgroundColor: '#dca0ce' },
  unknown: { backgroundColor: '#545454' },
  shadow: { backgroundColor: '#364163' },
};
